// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TaskResponseStatus.
const (
	TaskResponseStatusCompleted TaskResponseStatus = "completed"
	TaskResponseStatusFailed    TaskResponseStatus = "failed"
	TaskResponseStatusPending   TaskResponseStatus = "pending"
	TaskResponseStatusRunning   TaskResponseStatus = "running"
)

// Defines values for GetTasksParamsStatus.
const (
	GetTasksParamsStatusCompleted GetTasksParamsStatus = "completed"
	GetTasksParamsStatusFailed    GetTasksParamsStatus = "failed"
	GetTasksParamsStatusPending   GetTasksParamsStatus = "pending"
	GetTasksParamsStatusRunning   GetTasksParamsStatus = "running"
)

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	// Command Command and arguments to execute
	Command []string `json:"command"`

	// Schedule Cron expression for task scheduling
	Schedule string `json:"schedule"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error message
	Error *string `json:"error,omitempty"`
}

// TaskListResponse defines model for TaskListResponse.
type TaskListResponse struct {
	// Count Number of tasks returned
	Count *int `json:"count,omitempty"`

	// Tasks List of tasks
	Tasks *[]TaskResponse `json:"tasks,omitempty"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	// Command Command and arguments to execute
	Command *[]string `json:"command,omitempty"`

	// CreatedAt Task creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Unique task identifier
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Schedule Cron expression for task scheduling
	Schedule *string `json:"schedule,omitempty"`

	// Status Current task status
	Status *TaskResponseStatus `json:"status,omitempty"`

	// UpdatedAt Task last update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TaskResponseStatus Current task status
type TaskResponseStatus string

// GetTasksParams defines parameters for GetTasks.
type GetTasksParams struct {
	// Status Filter tasks by status
	Status *GetTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetTasksParamsStatus defines parameters for GetTasks.
type GetTasksParamsStatus string

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List tasks
	// (GET /api/v1/tasks)
	GetTasks(c *gin.Context, params GetTasksParams)
	// Create a new task
	// (POST /api/v1/tasks)
	CreateTask(c *gin.Context)
	// Get a task by ID
	// (GET /api/v1/tasks/{id})
	GetTask(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetTasks operation middleware
func (siw *ServerInterfaceWrapper) GetTasks(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTasksParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTasks(c, params)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTask(c)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTask(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/tasks", wrapper.GetTasks)
	router.POST(options.BaseURL+"/api/v1/tasks", wrapper.CreateTask)
	router.GET(options.BaseURL+"/api/v1/tasks/:id", wrapper.GetTask)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXW2/bNhT+KwTXhyaQLcl20tZP29q1M9BtRZu+rPEGWjq22EokQx46NVL/94GkfNEl",
	"TTb0MrSBDInnwsPv+87hDc1kpaQAgYZOb6jJCqiY//lUA0O4YObDa7iyYNC9VFoq0MjBL8lkVTGRu585",
	"mExzhVwKOqVPwwfi//TKVs4/QUngI2QWgUYUPrJKlUCn7yhkhaQRLaAsJbmWuszpPKIcofJRcKOATqlB",
	"zcWKbiNacTELH9No95VpzTbuo9tBbp3jTlJaCgIflQZjuBRkKTVBZj6Q2sR5P8qLJuQ0PiOn4R+NqGKI",
	"oJ2nvx5eXp5+evguGTyZf0rDYxQe4/CYhMeZf5x8urw8vbyM729wQr5bhPFnnI2P7NL+QOmR+e1Lul5G",
	"fXajRp7njczO5ycnD2jURsc2ohquLNeQO2jt0RDtwTrf28jFe8jQgeYXraV+DUZJYaCLc3Cfu4DyVqQC",
	"Y9iqAWk6E2tW8jzAa/asN81OEo5qL7nB2/PIpBXYzeN3Wy1AE7n08QzRgFYLyI9TSpN9RC4QVqBdSL++",
	"69BlsXdHj6j4QMOSTukP8UE14loy4qAUderbNjFv2/DnNvtdxKWtJ5mXwfxv1lN4twHiFzg9QV6BQVap",
	"BhRGyWg8SNJBkl4kydT//5NGdCl15VzSnCEMnGkXJBHlPdt/K/iVhQAtnoNAvuSgGzHT0RgmZ+ePBvD4",
	"yWKQjvLxgE3OzgeT0fl5OkkfTZIkOc7BWp73hf96WtoNhQxtDxSfWq1BYO08LIooCFu5w1Ug8hBKWyHC",
	"LwfNEtDDf8l4Cf7AD6kcbDpJWJV//qxLZpCEVV/+uLsUca+4WMpAB4Es84lBxXjpDK1SUuOPrjbLUl4P",
	"M1nRiApWQZ3w81Jek59ezcibsJRG1GpnWiAqM43jFcfCLpxhXBQsg3jny5WjVYACSMW4IAb0mmfgz7xi",
	"gq24WO3OHfJag7ggWADZJ2E2BqEakouCm72Hgom8BEOYxcIBOfNEiogOAwfxIlq/a6Er8vRXoA03CCKD",
	"IY1oyTOotaQuwm+zi86epQJhpNUZDKVexbWRid1adwYcy0b93tRb066SNKJrF9SXJB0mw8TZOJdMcTql",
	"42EyHIdhofBwjpni8TqN91K7gh50vQbUHNZAGCmPxZdccyyI9MtYWROALHmJoAOInWT6Es1yOqUvAC9q",
	"0VZMswoQtKHTd+14z72HOsZic8SsHp5wZ3FlQW8O6NobBPn3sPzXpGwTYO6ad+gHvlSjJNlBH0LjY0qV",
	"NUzi98Zt5eYog7vaU6O7enZ1Oe7bpz+LnBibZWDM0pal7wVnXzCf5sjRk8xMuGnTHTroNWgShhC3ztiq",
	"Ynqza9S7Lo1s5Y467ILOtxFV0mCfdruORhgRcN3ibYBb1hJ3x7RdN24D7nBLoGHyAoM/y3xzjzrtoXbU",
	"62/r14dO1Gol2+ie9e5eZ7bNYRG1hW0HgOkXBeBd4CP1tNFB3uTbIi9MrzsZVmxTSpb/LxnQADMGGLaJ",
	"sI2aKhzf8Hx7Hyk2CjK+5FngxmJDOBpiw/zVGL16RfguDb4IlwPy8O3b2bOT/zLAeWF2neagy36Qa4L6",
	"mCF3jHxfXYHvJMDt4vtdKFBf4EhdN5/G5Nul4UsiJJKltCJvQf8FIGF7aIZbZhv5zsCTpw+AL2XGSpLD",
	"Gkqp3C2qJlpjYprGcenWFdLg9HHyOKXbqO3olZa5zfwlqMeDm7mY4sPGmOqQVmfb9vYrsNJ1oQKyD2TP",
	"LHPAeFjQk8cf+8WELaQ9tMajkdjQ7Xz7TwAAAP//kQbF8fcSAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
