// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for TaskResponseStatus.
const (
	TaskResponseStatusCompleted TaskResponseStatus = "completed"
	TaskResponseStatusFailed    TaskResponseStatus = "failed"
	TaskResponseStatusPending   TaskResponseStatus = "pending"
	TaskResponseStatusRunning   TaskResponseStatus = "running"
)

// Defines values for GetTasksParamsStatus.
const (
	GetTasksParamsStatusCompleted GetTasksParamsStatus = "completed"
	GetTasksParamsStatusFailed    GetTasksParamsStatus = "failed"
	GetTasksParamsStatusPending   GetTasksParamsStatus = "pending"
	GetTasksParamsStatusRunning   GetTasksParamsStatus = "running"
)

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	// Command Command and arguments to execute
	Command []string `json:"command"`

	// Schedule Cron expression for task scheduling
	Schedule string `json:"schedule"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error message
	Error *string `json:"error,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Database Database connection status
	Database *string `json:"database,omitempty"`

	// Error Error message if unhealthy
	Error *string `json:"error,omitempty"`

	// Service Service name
	Service *string `json:"service,omitempty"`

	// Status Service health status
	Status *HealthResponseStatus `json:"status,omitempty"`
}

// HealthResponseStatus Service health status
type HealthResponseStatus string

// TaskListResponse defines model for TaskListResponse.
type TaskListResponse struct {
	// Count Number of tasks returned
	Count *int `json:"count,omitempty"`

	// Tasks List of tasks
	Tasks *[]TaskResponse `json:"tasks,omitempty"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	// Command Command and arguments to execute
	Command *[]string `json:"command,omitempty"`

	// CreatedAt Task creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Unique task identifier
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Schedule Cron expression for task scheduling
	Schedule *string `json:"schedule,omitempty"`

	// Status Current task status
	Status *TaskResponseStatus `json:"status,omitempty"`

	// UpdatedAt Task last update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TaskResponseStatus Current task status
type TaskResponseStatus string

// GetTasksParams defines parameters for GetTasks.
type GetTasksParams struct {
	// Status Filter tasks by status
	Status *GetTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetTasksParamsStatus defines parameters for GetTasks.
type GetTasksParamsStatus string

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List tasks
	// (GET /api/v1/tasks)
	GetTasks(c *gin.Context, params GetTasksParams)
	// Create a new task
	// (POST /api/v1/tasks)
	CreateTask(c *gin.Context)
	// Get a task by ID
	// (GET /api/v1/tasks/{id})
	GetTask(c *gin.Context, id openapi_types.UUID)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetTasks operation middleware
func (siw *ServerInterfaceWrapper) GetTasks(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTasksParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTasks(c, params)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTask(c)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTask(c, id)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/tasks", wrapper.GetTasks)
	router.POST(options.BaseURL+"/api/v1/tasks", wrapper.CreateTask)
	router.GET(options.BaseURL+"/api/v1/tasks/:id", wrapper.GetTask)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYbW/bOBL+KwSvH5pAjiTbSVt/ul567Rno7RZt+mUb74KmxhZbiVT44tRI/d8XJGW9",
	"O3GLvizawIbFGT5DPvPMjO4wFXkhOHCt8OwOK5pCTtzXSwlEwxVRn97CjQGl7Y+FFAVIzcAtoSLPCU/s",
	"1wQUlazQTHA8w5f+AXJ/cm1y6x9pgeAzUKMBBxg+k7zIAM8+YKCpwAFOIcsEuhUyS/AiwExD7nbR2wLw",
	"DCstGV/jXYBzxuf+YRzsnxIpydY+tBEkxjrugZKCI/hcSFCKCY5WQiJN1CdUmljvDVw4QqfhOTr1/3CA",
	"C6I1SOvpz8fX16dfHn+IRs8WX2L/MfYfE/8x9R/n7uPky/X16fV1eLzBCfplO0zucTZp2MXDG8UN88NL",
	"+l7GQ3bjFs6LFrKLxcnJIxx02bELsIQbwyQklloVG4KKrIvKRiw/AtWWNP+VUsi3oArBFfR5DvZxn1DO",
	"CuWgFFm3KI3nfEMylnh6zV8MwuyB+B+QTKeHUSREkyVRA8x+UT5BVHAO1P6KlCbaqBaq8ikkfTzBUTEi",
	"tkKGpw7ntuU6GUCwIiwb3kuB3DA6EMg7/wBxkrcPdH+PctCdD/WgNw+4cSLc5JYcdSB1UIvmrvWCI67P",
	"KuVrpvThC6TCcN2H+ZvJlyCRWDm6KCRBG8ndyVVQ4qjakXENa5B2S7e+79CiqNzhhpI+krDCM/yvsBb9",
	"sFT80At9CX3X1dVDAd8X7C+pDd1yQF0VS/4iAwdvA0BugaWrZjkoTfKiRbxxNJ6MongUxVdRNHP//8AB",
	"XgmZW5eW+DCypkPEZAPhv+fsxoBXBpYA12zFHK3rPePxBKbnF09G8PTZchSPk8mITM8vRtPxxUU8jZ9M",
	"oyhqYjCGDafZDyuFR6fgpZESuC6ddxOwAJ74raTh3H+z1MzAi1SpIK2crG16IEyR3H/XGVEa+VXf/7r7",
	"KWJ/YnwlfDpwTagDBjlhmTU0RSGk/rc9m1Umbs+oyHGAnfZ5wC8zcYuev5mjd36pVSppTVOtCzULwzXT",
	"qVlawzBNCYVw78seR/sAnqOcUSlK6XU3nhNO1oyv97cOSalAjCOdAqogqK3SYLFljEKZ7SXM/8+veqhE",
	"AVwJIymcCbkOSyMV2rX2lJjOWhG+24u7jRUHeANSedDxWXQWWRvrkhQMz/DkLDqb+G4sdYQLScHCTRxW",
	"YriGgft/C1oy2AAiKGvKI7plOkXCLSNZSVG0YpkG6WlmRc0pxDzBM/wK9FUpqwWRJAcNUuHZh+5+L52H",
	"co/ldqgc10xm1uLGgNzW918ZeIF2xPnqtOlSdGG7I6/Y7qjGUbQnJ/jSRIoiY9TFG35UNpS7BoKHCkir",
	"/jn+97PQFTh3FwlShlJQamWyzKn1+XfE0+7pBsDMuW3n7aWD3IBEvgOy65TJcyK3+1K6r6OarO1V+yjw",
	"YhfgQig9pK625iCCONx2csvTjXbk15bCfb3sEq4ew7BvbUHp/4hke8Q5VVRrVONDFbWuFR2x3wVHnnd/",
	"Xty1u3EtDex6BIy/KwEfIh8q+4Ee86Y/l3l+PCivExVkmwmS/CMzoEVm7WnYTYRd0Fbh8I4lu2OkWBVA",
	"2YpRnxvLLWJaIeM7pFZzNCjCD2nwlZ++0OP37+cvTr6lxXLCbCtNrcuu1WqTupkhDzRlP1yBH0yAw+L7",
	"S1KgnJBReW4OxvTnwXBHwoVGK2F40qH+K9CIVNT0Y/wA8/2UeJDulynQT66fas2hrgNJoaoPEu2n4gG2",
	"+1cD+Ju406gC9RuE1ruAahxvjdn7lr6ago+uBJ0XGQPHvp/MmUIN7+fR5OviKd9Z3P/24YHo6tH/x8TX",
	"8N8il3eCqGVHg1jlTS+cUy/LQ9L2WlCSoQQ2kInCTtClhLd68VkYZnZdKpSePY2exngXdB29kSIx5Ruj",
	"vgfbzZOCnbVGFKthJdyut2ZQqGKxqtWzDK+P4/dqMSJLYeqmqzEOKbxb7P4OAAD//8ViGwmyFgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
